name: Dagelijkse scraper get_athlete_data

on:
    schedule:
        - cron: '0 * * * *'  # Elk uur
    workflow_dispatch:  # Voor handmatige runs

jobs:
  run-scrapers:
    runs-on: ubuntu-latest

    steps:
    - name: Haal de code op
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Zorgt dat push altijd goed werkt

    - name: Zet Python op
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Installeer dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Draai scraper
      run: |
        python scripts/get_athlete_data.py

    - name: Upload de gegenereerde CSV
      uses: actions/upload-artifact@v4
      with:
        name: scraper-output
        path: data/

    - name: Commit & push CSV
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/${{ github.repository }}
        git status
        git diff
        git add data/*.csv
        if git diff --cached --quiet; then
            echo "Geen wijzigingen in CSV, dus geen commit."
        else
            git commit -m "Automatisch bijgewerkte CSV"
            git push
        fi

