name: Dagelijkse scrapers run

on:
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch:  # Voor handmatige runs

jobs:
  run-scrapers:
    runs-on: ubuntu-latest

    steps:
    - name: Haal de code op
      uses: actions/checkout@v4

    - name: Zet Python op
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Pas aan als nodig

    - name: Installeer dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Draai scraper 1
      run: |
        python scripts/get_athlete_data.py  # Pas aan naar juiste bestandsnaam

    - name: Draai scraper 2
      run: |
        python scripts/get_transfer_data.py  # Pas aan naar juiste bestandsnaam

    - name: Upload de gegenereerde CSV’s
      uses: actions/upload-artifact@v4
      with:
        name: scraper-output
        path: |
          output/  # Zet hier de map waar je CSV's worden opgeslagen (pas aan als nodig)

    - name: Commit & push CSVs
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/${{ github.repository }}
        git add output/*.csv
        if git diff --cached --quiet; then
            echo "Geen wijzigingen in CSV's, dus geen commit."
        else
            git commit -m "Automatisch bijgewerkte CSVs"
            git push
        fi

